[package]
name = "rustmydetection"
version = "1.0.0"
authors = ["frack113"]

build = "build.rs"

[build-dependencies]
winres = "0.1"
winapi = {version = "0.3.9",  features = ["winnt"]}

[dependencies]
winreg = "0.50"
